name: ip_info
description: "A Simple IP Locator for Android"
publish_to: 'none' # Prevent publishing to pub.dev

version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking and utilities
  http: ^1.3.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  maps_launcher: ^3.0.0+1

  # UI and icons
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.6

  # Launcher icon generator
  flutter_launcher_icons: any
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets for launcher icons or other uses
  assets:
    - assets/main.png

flutter_launcher_icons:
  android: true
  adaptive_icon_foreground: "assets/main.png"
  adaptive_icon_background: "#e3e3e3"
  ios: true
  web:
    generate: true
    image_path: "assets/main.png"
  windows:
    generate: true
    image_path: "assets/main.png"
  macos:
    generate: true
    image_path: "assets/main.png"
  linux:
    generate: true
    image_path: "assets/main.png"
  image_path: "assets/main.png"
